### ISSUE TITLE
Add comprehensive word to magic number converting time index to time

### ISSUE THREAD

**Issue by Sakumatcho** [moonshot-nagayama-pj/multiharp-toolkit#13]
SEE https://github.com/moonshot-nagayama-pj/multiharp-toolkit/pull/9#pullrequestreview-2188375402

1. Add comprehensive word to magic number "5"
2. Make comprehensive function calculating `timestamp * 5`

**Comment by Sakumatcho** [comment]
Extra "globRes"s are found...

- https://github.com/moonshot-nagayama-pj/multiharp-toolkit/blob/main/src/multiharp_toolkit/ptu_parser_test.py#L16
- https://github.com/moonshot-nagayama-pj/multiharp-toolkit/blob/main/src/multiharp_toolkit/ptu_parser.py#L29
- https://github.com/moonshot-nagayama-pj/multiharp-toolkit/blob/main/src/multiharp_toolkit/ptu_parser.py#L207-L208

I do not understand whether I should fix these "globRes"s to "time_resolution" as I fixed in #11 .
It seems not to be used in any other codes in this repository, but I am not sure in other repository if the other repos import this repo.
If these are not used in any other repositories actually, should I fix these in this issue or another issue?

**Comment by auspicacious** [comment]
@Sakumatcho 

> Add comprehensive word to magic number "5"

I'm not sure what "comprehensive word" means.

By the way, this is better called a "hard-coded value" instead of a "magic number." "Magic number" has too many other meanings.

The code containing `globRes` is demo code written by PicoQuant. [See the header](https://github.com/moonshot-nagayama-pj/multiharp-toolkit/blob/main/src/multiharp_toolkit/ptu_parser.py#L5).

mixedCase variable names like `globRes` are strongly discouraged in Python by [PEP 8](https://peps.python.org/pep-0008/#function-and-variable-names).

It looks like we should probably clean up this code in a separate issue. Also, I think that the code in https://github.com/moonshot-nagayama-pj/multiharp-toolkit/pull/11 can be made much clearer, but it will take some work.
